### ISSUE TITLE
Questions with the f-scLVM.ipynb

### ISSUE THREAD

**Issue by wgmao** [PMBio/f-scLVM#2]
I just tried to reproduce the results by f-scLVM.ipynb but I met some problems which made it incomplete. I use "Buettneretal2015.hdf5" as the source for pathway information and the problems are listed as follows,

1. `gene_ids = data['genes']` should be corrected to `gene_ids = data['sym_names']`

2.  `X = FA.getX(terms=['G2m checkpoint','P53 pathway'])` should be corrected to `X = FA.getX(terms=['G2M_CHECKPOINT','P53_PATHWAY'])`

3. `fig = plotFactors(X=X, lab=data['lab'], terms=['G2m checkpoint','P53 pathway'], isCont=False)`

There is no 'lab' key in the 'data' and 'data' only contains the following keys,
`known_names, terms, sym_names, I, IR20, Known, termsR, Y`. I couldn't figure out which one is the 'lab' referred here.

Thanks for the repository and the paper on biorxiv. I really like this work.

**Comment by flophys** [comment]
Apologies, the notebook was already adapted for the new version in the devel branch - I have now merged the codebase into master and with the latest version this will work as in the notebook
